language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-gulp-ng-coffee' ]; then cd .. && eval "mv $currentfolder generator-gulp-ng-coffee" && cd generator-gulp-ng-coffee; fi

